# Generated by Django 2.0.6 on 2018-06-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbing', '0002_auto_20180611_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='description',
            field=models.TextField(blank=True, verbose_name='Event description'),
        ),
    ]
