# Generated by Django 2.1.1 on 2018-10-09 15:16

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('climbing', '0002_auto_20180831_1154'),
    ]

    def create_default_gender(apps, schema_editor):
        Gender = apps.get_model('climbing', 'Gender')
        m = Gender(name="male")
        m.save()
        f = Gender(name="female")
        f.save()

    def update_athletes_gender(apps, schema_editor):
        Gender = apps.get_model('climbing', 'Gender')
        m = Gender.objects.get(name="male")
        f = Gender.objects.get(name="female")
        Athlete = apps.get_model('climbing', 'Athlete')
        athletes = Athlete.objects.raw("SELECT *, gender_id AS old_gender FROM climbing_athlete")
        for a in athletes:
            if a.old_gender == "M":
                a.gender = m
            else:
                a.gender = f
            a.save()

# First create Gender model and default values,
# then updates other models and existing objects.

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['code'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.RunPython(create_default_gender),

        migrations.AddField(
            model_name='boulder',
            name='categories',
            field=models.ManyToManyField(to='climbing.Category'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='climbing.Gender'),
        ),
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='climbing.Gender'),
            preserve_default=False,
        ),
        migrations.RunPython(update_athletes_gender),
    ]
