# Generated by Django 2.0.6 on 2018-06-12 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climbing', '0003_auto_20180611_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, verbose_name='Code')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_nbr', models.PositiveIntegerField(verbose_name='Route number')),
                ('result', models.PositiveSmallIntegerField(choices=[(0, 'failure'), (1, 'zone'), (2, 'top')])),
            ],
        ),
        migrations.CreateModel(
            name='Subcompetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100)),
                ('min_route_nbr', models.PositiveIntegerField(default=1, verbose_name='Minimum route ID')),
                ('max_route_nbr', models.PositiveIntegerField(default=40, verbose_name='Maximum route ID')),
                ('top_value', models.PositiveIntegerField(default=1000, verbose_name='Value for top')),
                ('zone_value', models.PositiveIntegerField(default=0, verbose_name='Value for zone')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='climbing.Category')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climbing.Competition')),
            ],
        ),
        migrations.RemoveField(
            model_name='boulder',
            name='competition',
        ),
        migrations.AlterField(
            model_name='athlete',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climbing.Category'),
        ),
        migrations.DeleteModel(
            name='Boulder',
        ),
        migrations.AddField(
            model_name='result',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='climbing.Athlete'),
        ),
        migrations.AddField(
            model_name='result',
            name='subcompetition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='climbing.Subcompetition'),
        ),
        migrations.AddField(
            model_name='competition',
            name='categories',
            field=models.ManyToManyField(to='climbing.Category'),
        ),
    ]
