# Generated by Django 2.0.6 on 2018-06-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbing', '0004_auto_20180612_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcompetition',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], default='M', max_length=1, verbose_name='Gender'),
        ),
    ]
