# Generated by Django 2.0.6 on 2018-06-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbing', '0006_auto_20180612_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcompetition',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subcompetition',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='result',
            name='route_nbr',
        ),
        migrations.AddField(
            model_name='result',
            name='boulder_nbr',
            field=models.PositiveIntegerField(default=1, verbose_name='Boulder number'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Subcompetition',
        ),
    ]
