# Generated by Django 2.0.6 on 2018-06-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbing', '0008_auto_20180612_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='competitions',
            field=models.ManyToManyField(to='climbing.Competition'),
        ),
    ]
