# Generated by Django 2.0.6 on 2018-06-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbing', '0009_athlete_competitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='max_boulder_nbr',
            field=models.PositiveIntegerField(default=40, verbose_name='Maximum boulder ID'),
        ),
        migrations.AddField(
            model_name='competition',
            name='min_boulder_nbr',
            field=models.PositiveIntegerField(default=1, verbose_name='Minimum boulder ID'),
        ),
    ]
