# Generated by Django 2.0.6 on 2018-06-14 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climbing', '0010_auto_20180612_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boulder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='ID number')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Description')),
                ('top_value', models.PositiveIntegerField(default=1000, verbose_name='Value for top')),
                ('zone_value', models.PositiveIntegerField(default=0, verbose_name='Value for zone')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='competition',
            name='code',
            field=models.TextField(default='XX', max_length=10, verbose_name='Event short code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boulder',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climbing.Competition'),
        ),
    ]
