# Generated by Django 2.0.6 on 2018-06-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbing', '0011_auto_20180614_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Event short code'),
        ),
    ]
