# Generated by Django 2.0.6 on 2018-06-14 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climbing', '0012_auto_20180614_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='boulder_nbr',
        ),
        migrations.AddField(
            model_name='result',
            name='boulder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='climbing.Boulder'),
            preserve_default=False,
        ),
    ]
