# Generated by Django 2.0.6 on 2018-06-14 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climbing', '0014_auto_20180614_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='category',
        ),
    ]
